CREATE TABLE raffle_number(
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    ticket_id BIGINT(20) UNSIGNED NOT NULL,
    numbers json NOT NULL DEFAULT (JSON_ARRAY()),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key (id),
    CONSTRAINT `ticketId` foreign key  (ticket_id) REFERENCES ticket(id) ON DELETE CASCADE
);