CREATE TABLE ticket(
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    drawn boolean NOT NULL DEFAULT false,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key (id)
);